### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by BenMKT** [BenMKT/Recipe-App#10]
- Kindly find our [Github Repo](https://github.com/BenMKT/receipe_app) for review on the Kanban board setup.
- We are 2 people collaborating on this project.

**Comment by julie-ify** [comment]
Hi @BenMKT and @waelelsafty07,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

* Kindly provide the link to the Kanban, instead of your repository.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by BenMKT** [comment]
- Kindly find our updated [Github Repo](https://github.com/BenMKT/receipe_app/projects/1) for review on the Kanban board setup.
- We are 2 people collaborating on this project.

**Comment by aamirkhan2478** [comment]
Hi @BenMKT & @waelelsafty07, 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good commit messages
✅ Good descriptive PR
✅ Added the `To Do` column to the board
✅ Added the `In Progress` column to the board
✅ Added the `In Review` column to the board
✅ Added the `Done` column to the board
✅ Assigned tasks equally 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
